language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
services:
  - docker
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_9a0bf0ad51c4_key -iv $encrypted_9a0bf0ad51c4_iv -in secrets/secrets.yml.enc -out secrets/secrets.yml -d
install:
  - npm install -g serverless
  - npm install
  - npm run vue:install
script:
  - npm run docker:build
  - npm run build
  - serverless deploy --stage prod
