service: racket-serverless

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1

plugins:
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  environments:
    prod:
      LAMBDA: dist/handler.app
      EXEC_PATH: ./linux-application
    dev:
      LAMBDA: src/api/handler.app
      EXEC_PATH: ./dev/application

package:
  include:
    - dist/**
  exclude:
    - /**

functions:
  api:
    handler: ${self:custom.environments.${self:custom.stage}.LAMBDA}
    environment: ${self:custom.environments.${self:custom.stage}}
    events:
      - http:
          path: /{proxy+}
          method: any
