service: racket-serverless

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1

plugins:
  - serverless-offline
  - serverless-finch

custom:
  stage: ${opt:stage, self:provider.stage}
  client:
    bucketName: racket-api-client
    distributionFolder: packages/frontend/dist
  environments:
    prod:
      LAMBDA_PATH: packages/api/dist/handler.app
      EXEC_PATH: ./packages/api/dist/linux-application
      DATABASE_HOST: ${file(secrets/secrets.yml):PROD_DATABASE_HOST}
      DATABASE_API_KEY: ${file(secrets/secrets.yml):PROD_DATABASE_API_KEY}
    dev:
      LAMBDA_PATH: packages/api/src/handler.app
      EXEC_PATH: ./packages/api/dev/application
      DATABASE_HOST: ${file(secrets/secrets.yml):DEV_DATABASE_HOST}
      DATABASE_API_KEY: ${file(secrets/secrets.yml):DEV_DATABASE_API_KEY}

package:
  individually: true
  exclude:
    - ./**

functions:
  api:
    handler: ${self:custom.environments.${self:custom.stage}.LAMBDA_PATH}
    environment: ${self:custom.environments.${self:custom.stage}}
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
    package:
      include:
        - secrets/**
        - packages/api/dist/**
